name: Build and Release PiPCam

on:
    push:
        tags:
            - "v*" # Dispara quando você cria uma tag começando com 'v' (ex: v1.2.3)
    workflow_dispatch:
        # Permite rodar manualmente se necessário

jobs:
    release:
        runs-on: windows-latest
        permissions:
            contents: write # Necessário para criar a release e fazer upload do arquivo

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  enable-cache: true

            - name: Set up Python
              run: uv python install 3.12

            - name: Install dependencies
              run: |
                  uv sync
                  uv add pyinstaller

            - name: Build Executable
              run: |
                  uv run pyinstaller --noconsole --onefile --name "PiPCam" `
                  --add-data "classes;classes" `
                  --add-data "utils;utils" `
                  main.py

            - name: Create Release and Upload Asset
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/PiPCam.exe
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
